### ISSUE TITLE
good job!

### ISSUE THREAD

**Issue by simosentissi** [mortezaadi/ninja-activiti-module#1]
I was pretty glad to find this project! good job! 
are you using both in production ?

Cheers!
-S

**Comment by mortezaadi** [comment]
Hi,
Thanks, I'm not using the project in production. Mostly because I wasn't sure enough to pick up the ninja framework for a banking solution. However IMHO Ninja is pretty cool and now its time to give it a try. 

Best wishes,
Morteza
